### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: input and filter must have the same depth: 1664 vs 1

### ISSUE THREAD

**Issue by lzq2369** [relgukxilef/dense-depth-estimation#1]
when i run :python test.py  ,  the error is next:

OMP: Info #250: KMP_AFFINITY: pid 27268 tid 28058 thread 57 bound to OS proc set 25
OMP: Info #250: KMP_AFFINITY: pid 27268 tid 28065 thread 64 bound to OS proc set 0
OMP: Info #250: KMP_AFFINITY: pid 27268 tid 28039 thread 38 bound to OS proc set 6
OMP: Info #250: KMP_AFFINITY: pid 27268 tid 28056 thread 55 bound to OS proc set 23
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    outputs = predict(model, inputs)
  File "/home/wangwenzhong/project/lzq/DepthMap/dense-depth-estimation/DenseDepth-master/utils.py", line 10, in predict
    predictions = model.predict(images, batch_size=batch_size)
  File "/home/wangwenzhong/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 908, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/wangwenzhong/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 723, in predict
    callbacks=callbacks)
  File "/home/wangwenzhong/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 394, in model_iteration
    batch_outs = f(ins_batch)
  File "/home/wangwenzhong/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/home/wangwenzhong/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: input and filter must have the same depth: 1664 vs 1
         [[{{node conv2/BiasAdd}}]]

I don't know what is question ?  about "input and filter must have the same depth: 1664 vs 1
         [[{{node conv2/BiasAdd}}]]"

**Comment by relgukxilef** [comment]
Hello there. I am sorry I didn't mention it anywhere, but this project is actually just a fork of the project [https://github.com/ialhashim/DenseDepth](https://github.com/ialhashim/DenseDepth)
I'm afraid I can't help you with your problem right now but you might be able to find help at the project page I linked above.
